repos:
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v2.3.0
    hooks:
      - id: stylua-system
  - repo: https://github.com/espressif/conventional-precommit-linter
    rev: v1.7.0
    hooks:
      - id: conventional-precommit-linter
        stages: [commit-msg]
